### upload building file
PUT https://localhost:2881/building
Authorization: Basic admin dickerelch
Content-Type: application/octet-stream

< /home/karen/Workspace/dcache/BUILDING.md

### upload readme file
PUT https://localhost:2881/readme
Authorization: Basic admin dickerelch
Content-Type: application/octet-stream

< /home/karen/Workspace/dcache/README.md

### make sure readme file is there
GET http://localhost:3880/api/v1/namespace/readme

### add "firststep" label to building file
# curl -X POST -u admin:dickerelch -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:3880/api/v1/namespace/building -d '{"action" : "set-label", "label" : "firststep" }'
POST http://localhost:3880/api/v1/namespace/building
Authorization: Basic admin dickerelch
Accept: application/json
Content-Type: application/json

{"action" : "set-label", "label" : "firststep" }

### add "blue" label to readme file
POST http://localhost:3880/api/v1/namespace/readme
Authorization: Basic admin dickerelch
Accept: application/json
Content-Type: application/json

{"action" : "set-label", "label" : "blue" }

### get file(s) that has "firststep" label
GET http://localhost:3880/api/v1/labels/firststep

### get file(s) that has "blue" label
GET http://localhost:3880/api/v1/labels/blue

### make sure "firststep" label is there
GET http://localhost:3880/api/v1/namespace/building/?labels=true

### make sure "blue" label is there
GET http://localhost:3880/api/v1/namespace/readme/?labels=true

### remove "blue" label
POST http://localhost:3880/api/v1/namespace/readme
Authorization: Basic admin dickerelch
Accept: application/json
Content-Type: application/json

{"action" : "rm-label", "label" : "blue" }

### make sure "blue" label is NOT in readme file
GET http://localhost:3880/api/v1/namespace/readme/?labels=true



