### upload building file
PUT https://localhost:2881/building
Authorization: Basic admin dickerelch
Content-Type: application/octet-stream

< /home/karen/Workspace/dcache/BUILDING.md

### make sure file is there
GET {{localhost-3880}}/{{api}}/{{v1}}/{{namespace}}/building

### add a label
# curl -X POST -u admin:dickerelch -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:3880/api/v1/namespace/building -d '{"action" : "set-label", "label" : "firststep" }'
POST http://localhost:3880/api/v1/namespace/building
Authorization: Basic admin dickerelch
Accept: application/json
Content-Type: application/json

{"action" : "set-label", "label" : "firststep" }

###


